# frozen_string_literal: true

#  Copyright (c) 2024, Schweizer Alpen-Club. This file is part of
#  hitobito_sac_cas and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sac_cas.

QualificationKind.seed(:id,
  {id: 1, tourenchef_may_edit: true},
  {id: 2, tourenchef_may_edit: true},
  {id: 3, tourenchef_may_edit: true},
  {id: 4, tourenchef_may_edit: true},
  {id: 5, tourenchef_may_edit: true},
  {id: 6, tourenchef_may_edit: true},
  {id: 7, tourenchef_may_edit: true},
  {id: 8, tourenchef_may_edit: true},
  {id: 9, tourenchef_may_edit: false},
  {id: 10, tourenchef_may_edit: false},
  {id: 11, tourenchef_may_edit: true},
  {id: 12, tourenchef_may_edit: false, validity: 6, reactivateable: 4, required_training_days: 3},
  {id: 13, tourenchef_may_edit: false, validity: 6, reactivateable: 4, required_training_days: 3},
  {id: 14, tourenchef_may_edit: false, validity: 6, reactivateable: 4, required_training_days: 3},
  {id: 15, tourenchef_may_edit: false, validity: 6, reactivateable: 4, required_training_days: 3},
  {id: 16, tourenchef_may_edit: false, validity: 6, reactivateable: 4, required_training_days: 3},
  {id: 17, tourenchef_may_edit: false, validity: 6, reactivateable: 4, required_training_days: 3},
  {id: 18, tourenchef_may_edit: false, validity: 6, reactivateable: 4, required_training_days: 3},
  {id: 19, tourenchef_may_edit: false, validity: 6, reactivateable: 4, required_training_days: 3},
  {id: 20, tourenchef_may_edit: false},
  {id: 21, tourenchef_may_edit: false, validity: 6, reactivateable: 4, required_training_days: 3},
  {id: 22, tourenchef_may_edit: false, validity: 6, reactivateable: 4, required_training_days: 3},
  {id: 23, tourenchef_may_edit: true},
  {id: 24, tourenchef_may_edit: true},
  {id: 25, tourenchef_may_edit: true},
  {id: 26, tourenchef_may_edit: true},
  {id: 27, tourenchef_may_edit: true},
  {id: 28, tourenchef_may_edit: true},
  {id: 29, tourenchef_may_edit: true})

QualificationKind::Translation.seed(:qualification_kind_id, :locale,
  {qualification_kind_id: 1, locale: "de", label: "Bergführer Aspirant*in"},
  {qualification_kind_id: 1, locale: "fr", label: "Bergführer Aspirant*in"},
  {qualification_kind_id: 1, locale: "it", label: "Bergführer Aspirant*in"},
  {qualification_kind_id: 1, locale: "en", label: "Bergführer Aspirant*in"},
  {qualification_kind_id: 2, locale: "de", label: "Bergführer*in SBV"},
  {qualification_kind_id: 2, locale: "fr", label: "Bergführer*in SBV"},
  {qualification_kind_id: 2, locale: "it", label: "Bergführer*in SBV"},
  {qualification_kind_id: 2, locale: "en", label: "Bergführer*in SBV"},
  {qualification_kind_id: 3, locale: "de", label: "Bikeleiter*in"},
  {qualification_kind_id: 3, locale: "fr", label: "Bikeleiter*in"},
  {qualification_kind_id: 3, locale: "it", label: "Bikeleiter*in"},
  {qualification_kind_id: 3, locale: "en", label: "Bikeleiter*in"},
  {qualification_kind_id: 4, locale: "de", label: "Diverse Leiter*in"},
  {qualification_kind_id: 4, locale: "fr", label: "Diverse Leiter*in"},
  {qualification_kind_id: 4, locale: "it", label: "Diverse Leiter*in"},
  {qualification_kind_id: 4, locale: "en", label: "Diverse Leiter*in"},
  {qualification_kind_id: 5, locale: "de", label: "Fitnessleiter*in"},
  {qualification_kind_id: 5, locale: "fr", label: "Fitnessleiter*in"},
  {qualification_kind_id: 5, locale: "it", label: "Fitnessleiter*in"},
  {qualification_kind_id: 5, locale: "en", label: "Fitnessleiter*in"},
  {qualification_kind_id: 6, locale: "de", label: "Gleitschirmleiter*in"},
  {qualification_kind_id: 6, locale: "fr", label: "Gleitschirmleiter*in"},
  {qualification_kind_id: 6, locale: "it", label: "Gleitschirmleiter*in"},
  {qualification_kind_id: 6, locale: "en", label: "Gleitschirmleiter*in"},
  {qualification_kind_id: 7, locale: "de", label: "Höhlenleiter*in"},
  {qualification_kind_id: 7, locale: "fr", label: "Höhlenleiter*in"},
  {qualification_kind_id: 7, locale: "it", label: "Höhlenleiter*in"},
  {qualification_kind_id: 7, locale: "en", label: "Höhlenleiter*in"},
  {qualification_kind_id: 8, locale: "de", label: "Kletterlehrer*in SBV"},
  {qualification_kind_id: 8, locale: "fr", label: "Kletterlehrer*in SBV"},
  {qualification_kind_id: 8, locale: "it", label: "Kletterlehrer*in SBV"},
  {qualification_kind_id: 8, locale: "en", label: "Kletterlehrer*in SBV"},
  {qualification_kind_id: 9, locale: "de", label: "Leiter*in Familienbergsteigen"},
  {qualification_kind_id: 9, locale: "fr", label: "Leiter*in Familienbergsteigen"},
  {qualification_kind_id: 9, locale: "it", label: "Leiter*in Familienbergsteigen"},
  {qualification_kind_id: 9, locale: "en", label: "Leiter*in Familienbergsteigen"},
  {qualification_kind_id: 10, locale: "de", label: "Leiter*in Kinderbergsteigen"},
  {qualification_kind_id: 10, locale: "fr", label: "Leiter*in Kinderbergsteigen"},
  {qualification_kind_id: 10, locale: "it", label: "Leiter*in Kinderbergsteigen"},
  {qualification_kind_id: 10, locale: "en", label: "Leiter*in Kinderbergsteigen"},
  {qualification_kind_id: 11, locale: "de", label: "SAC Tourenleiter - Aspirant*in"},
  {qualification_kind_id: 11, locale: "fr", label: "SAC Tourenleiter - Aspirant*in"},
  {qualification_kind_id: 11, locale: "it", label: "SAC Tourenleiter - Aspirant*in"},
  {qualification_kind_id: 11, locale: "en", label: "SAC Tourenleiter - Aspirant*in"},
  {qualification_kind_id: 12, locale: "de", label: "SAC Tourenleiter*in 1 Sommer"},
  {qualification_kind_id: 12, locale: "fr", label: "SAC Tourenleiter*in 1 Sommer"},
  {qualification_kind_id: 12, locale: "it", label: "SAC Tourenleiter*in 1 Sommer"},
  {qualification_kind_id: 12, locale: "en", label: "SAC Tourenleiter*in 1 Sommer"},
  {qualification_kind_id: 13, locale: "de", label: "SAC Tourenleiter*in 1 Sommer Senioren"},
  {qualification_kind_id: 13, locale: "fr", label: "SAC Tourenleiter*in 1 Sommer Senioren"},
  {qualification_kind_id: 13, locale: "it", label: "SAC Tourenleiter*in 1 Sommer Senioren"},
  {qualification_kind_id: 13, locale: "en", label: "SAC Tourenleiter*in 1 Sommer Senioren"},
  {qualification_kind_id: 14, locale: "de", label: "SAC Tourenleiter*in 1 Winter"},
  {qualification_kind_id: 14, locale: "fr", label: "SAC Tourenleiter*in 1 Winter"},
  {qualification_kind_id: 14, locale: "it", label: "SAC Tourenleiter*in 1 Winter"},
  {qualification_kind_id: 14, locale: "en", label: "SAC Tourenleiter*in 1 Winter"},
  {qualification_kind_id: 15, locale: "de", label: "SAC Tourenleiter*in 1 Winter Schneeschuhe"},
  {qualification_kind_id: 15, locale: "fr", label: "SAC Tourenleiter*in 1 Winter Schneeschuhe"},
  {qualification_kind_id: 15, locale: "it", label: "SAC Tourenleiter*in 1 Winter Schneeschuhe"},
  {qualification_kind_id: 15, locale: "en", label: "SAC Tourenleiter*in 1 Winter Schneeschuhe"},
  {qualification_kind_id: 16, locale: "de", label: "SAC Tourenleiter*in 1 Winter Senioren"},
  {qualification_kind_id: 16, locale: "fr", label: "SAC Tourenleiter*in 1 Winter Senioren"},
  {qualification_kind_id: 16, locale: "it", label: "SAC Tourenleiter*in 1 Winter Senioren"},
  {qualification_kind_id: 16, locale: "en", label: "SAC Tourenleiter*in 1 Winter Senioren"},
  {qualification_kind_id: 17, locale: "de", label: "SAC Tourenleiter*in 2 Sommer"},
  {qualification_kind_id: 17, locale: "fr", label: "SAC Tourenleiter*in 2 Sommer"},
  {qualification_kind_id: 17, locale: "it", label: "SAC Tourenleiter*in 2 Sommer"},
  {qualification_kind_id: 17, locale: "en", label: "SAC Tourenleiter*in 2 Sommer"},
  {qualification_kind_id: 18, locale: "de", label: "SAC Tourenleiter*in 2 Winter"},
  {qualification_kind_id: 18, locale: "fr", label: "SAC Tourenleiter*in 2 Winter"},
  {qualification_kind_id: 18, locale: "it", label: "SAC Tourenleiter*in 2 Winter"},
  {qualification_kind_id: 18, locale: "en", label: "SAC Tourenleiter*in 2 Winter"},
  {qualification_kind_id: 19, locale: "de", label: "SAC Tourenleiter*in Alpinwandern"},
  {qualification_kind_id: 19, locale: "fr", label: "SAC Tourenleiter*in Alpinwandern"},
  {qualification_kind_id: 19, locale: "it", label: "SAC Tourenleiter*in Alpinwandern"},
  {qualification_kind_id: 19, locale: "en", label: "SAC Tourenleiter*in Alpinwandern"},
  {qualification_kind_id: 20, locale: "de", label: "SAC Tourenleiter*in Bergwandern"},
  {qualification_kind_id: 20, locale: "fr", label: "SAC Tourenleiter*in Bergwandern"},
  {qualification_kind_id: 20, locale: "it", label: "SAC Tourenleiter*in Bergwandern"},
  {qualification_kind_id: 20, locale: "en", label: "SAC Tourenleiter*in Bergwandern"},
  {qualification_kind_id: 21, locale: "de", label: "SAC Tournleiter*in Mountainbike"},
  {qualification_kind_id: 21, locale: "fr", label: "SAC Tournleiter*in Mountainbike"},
  {qualification_kind_id: 21, locale: "it", label: "SAC Tournleiter*in Mountainbike"},
  {qualification_kind_id: 21, locale: "en", label: "SAC Tournleiter*in Mountainbike"},
  {qualification_kind_id: 22, locale: "de", label: "SAC Tourenleiter*in Sportklettern"},
  {qualification_kind_id: 22, locale: "fr", label: "SAC Tourenleiter*in Sportklettern"},
  {qualification_kind_id: 22, locale: "it", label: "SAC Tourenleiter*in Sportklettern"},
  {qualification_kind_id: 22, locale: "en", label: "SAC Tourenleiter*in Sportklettern"},
  {qualification_kind_id: 23, locale: "de", label: "Schneeschuhleiter*in bis WT4"},
  {qualification_kind_id: 23, locale: "fr", label: "Schneeschuhleiter*in bis WT4"},
  {qualification_kind_id: 23, locale: "it", label: "Schneeschuhleiter*in bis WT4"},
  {qualification_kind_id: 23, locale: "en", label: "Schneeschuhleiter*in bis WT4"},
  {qualification_kind_id: 24, locale: "de", label: "Schneesportlehrer*in"},
  {qualification_kind_id: 24, locale: "fr", label: "Schneesportlehrer*in"},
  {qualification_kind_id: 24, locale: "it", label: "Schneesportlehrer*in"},
  {qualification_kind_id: 24, locale: "en", label: "Schneesportlehrer*in"},
  {qualification_kind_id: 25, locale: "de", label: "Swiss Cycling MTB Guide"},
  {qualification_kind_id: 25, locale: "fr", label: "Swiss Cycling MTB Guide"},
  {qualification_kind_id: 25, locale: "it", label: "Swiss Cycling MTB Guide"},
  {qualification_kind_id: 25, locale: "en", label: "Swiss Cycling MTB Guide"},
  {qualification_kind_id: 26, locale: "de", label: "Walkingleiter*in"},
  {qualification_kind_id: 26, locale: "fr", label: "Walkingleiter*in"},
  {qualification_kind_id: 26, locale: "it", label: "Walkingleiter*in"},
  {qualification_kind_id: 26, locale: "en", label: "Walkingleiter*in"},
  {qualification_kind_id: 27, locale: "de", label: "Wanderleiter*in bis T2"},
  {qualification_kind_id: 27, locale: "fr", label: "Wanderleiter*in bis T2"},
  {qualification_kind_id: 27, locale: "it", label: "Wanderleiter*in bis T2"},
  {qualification_kind_id: 27, locale: "en", label: "Wanderleiter*in bis T2"},
  {qualification_kind_id: 28, locale: "de", label: "Wanderleiter*in bis T3"},
  {qualification_kind_id: 28, locale: "fr", label: "Wanderleiter*in bis T3"},
  {qualification_kind_id: 28, locale: "it", label: "Wanderleiter*in bis T3"},
  {qualification_kind_id: 28, locale: "en", label: "Wanderleiter*in bis T3"},
  {qualification_kind_id: 29, locale: "de", label: "Wanderleiter*in bis T4"},
  {qualification_kind_id: 29, locale: "fr", label: "Wanderleiter*in bis T4"},
  {qualification_kind_id: 29, locale: "it", label: "Wanderleiter*in bis T4"},
  {qualification_kind_id: 29, locale: "en", label: "Wanderleiter*in bis T4"})
