inherit_from:
  - ../hitobito/.rubocop.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - Rakefile
    - Gemfile
    - db/migrate/*
    - config/**/*
    - bin/**/*
    - tmp/**/*
    - lib/tty/**/*
