# frozen_string_literal: true

#  Copyright (c) 2025, Schweizer Alpen-Club. This file is part of
#  hitobito_sac_cas and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sac_cas.

Event::Discipline.seed_once(:id,
  {id: 1, order: 1},
  {id: 2, order: 2},
  {id: 3, order: 3},
  {id: 4, order: 4},
  {id: 11, order: 1, parent_id: 1},
  {id: 12, order: 2, parent_id: 1},
  {id: 13, order: 3, parent_id: 1},
  {id: 21, order: 1, parent_id: 2},
  {id: 22, order: 2, parent_id: 2},
  {id: 31, order: 1, parent_id: 3},
  {id: 32, order: 2, parent_id: 3},
  {id: 33, order: 3, parent_id: 3},
  {id: 34, order: 4, parent_id: 3},
  {id: 41, order: 1, parent_id: 4})

Event::Discipline::Translation.seed_once(:event_discipline_id, :locale,
  {event_discipline_id: 1,
   locale: "de",
   label: "Wandern",
   description: "Das Wandern ist des Müllers Lust"},
  {event_discipline_id: 2,
   locale: "de",
   label: "Hochtouren",
   description: "Obeuse"},
  {event_discipline_id: 3,
   locale: "de",
   label: "Klettern",
   description: "Chräsmä u Stägärä"},
  {event_discipline_id: 4,
   locale: "de",
   label: "Höhle",
   description: "Speläologie"},
  {event_discipline_id: 11,
   locale: "de",
   label: "Wanderweg",
   description: "Gemütlich dem Weg entlang"},
  {event_discipline_id: 12,
   locale: "de",
   label: "Bergtour",
   description: "Über Stock und Stein"},
  {event_discipline_id: 13,
   locale: "de",
   label: "Schneeschuhwandern",
   description: "Im Schnee läuft es sich besser mit grösserer Fläche"},
  {event_discipline_id: 21,
   locale: "de",
   label: "Skihochtouren",
   description: "Zwei Latten"},
  {event_discipline_id: 22,
   locale: "de",
   label: "Snowboardhochtouren",
   description: "Ein Brett"},
  {event_discipline_id: 31,
   locale: "de",
   label: "Fels",
   description: "Im harten Stein"},
  {event_discipline_id: 32,
   locale: "de",
   label: "Eis",
   description: "Schattig und kalt"},
  {event_discipline_id: 33,
   locale: "de",
   label: "Indoor",
   description: "Immer trocken, immer warm"},
  {event_discipline_id: 34,
   locale: "de",
   label: "Mehrseillängen",
   description: "Länger ist mehr"},
  {event_discipline_id: 41,
   locale: "de",
   label: "Höhle",
   description: "Speläologie"})
