# frozen_string_literal: true

#  Copyright (c) 2025, Schweizer Alpen-Club. This file is part of
#  hitobito_sac_cas and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sac_cas.

Event::Discipline.seed_once(:id,
  {id: 1, order: 1},
  {id: 2, order: 2},
  {id: 3, order: 3},
  {id: 4, order: 4},
  {id: 11, order: 1, parent_id: 1},
  {id: 12, order: 2, parent_id: 1},
  {id: 13, order: 3, parent_id: 1},
  {id: 21, order: 1, parent_id: 2},
  {id: 22, order: 2, parent_id: 2},
  {id: 31, order: 1, parent_id: 3},
  {id: 32, order: 2, parent_id: 3},
  {id: 33, order: 3, parent_id: 3},
  {id: 34, order: 4, parent_id: 3},
  {id: 41, order: 1, parent_id: 4})

Event::Discipline::Translation.seed_once(:event_discipline_id, :locale,
  {event_discipline_id: 1,
   locale: "de",
   label: "Wandern",
   description: "Das Wandern ist des Müllers Lust"},
  {event_discipline_id: 2,
   locale: "de",
   label: "Hochtouren",
   description: "Obeuse"},
  {event_discipline_id: 3,
   locale: "de",
   label: "Klettern",
   description: "Chräsmä u Stägärä"},
  {event_discipline_id: 4,
   locale: "de",
   label: "Höhle",
   description: "Speläologie"},
  {event_discipline_id: 11,
   locale: "de",
   label: "Wanderweg",
   description: "Gemütlich dem Weg entlang"},
  {event_discipline_id: 12,
   locale: "de",
   label: "Bergtour",
   description: "Über Stock und Stein"},
  {event_discipline_id: 13,
   locale: "de",
   label: "Schneeschuhwandern",
   description: "Im Schnee läuft es sich besser mit grösserer Fläche"},
  {event_discipline_id: 21,
   locale: "de",
   label: "Skihochtouren",
   description: "Zwei Latten"},
  {event_discipline_id: 22,
   locale: "de",
   label: "Snowboardhochtouren",
   description: "Ein Brett"},
  {event_discipline_id: 31,
   locale: "de",
   label: "Fels",
   description: "Im harten Stein"},
  {event_discipline_id: 32,
   locale: "de",
   label: "Eis",
   description: "Schattig und kalt"},
  {event_discipline_id: 33,
   locale: "de",
   label: "Indoor",
   description: "Immer trocken, immer warm"},
  {event_discipline_id: 34,
   locale: "de",
   label: "Mehrseillängen",
   description: "Länger ist mehr"},
  {event_discipline_id: 41,
   locale: "de",
   label: "Höhle",
   description: "Speläologie"})

Event::TargetGroup.seed_once(:id,
  {id: 1, order: 1},
  {id: 2, order: 2},
  {id: 3, order: 3},
  {id: 4, order: 4},
  {id: 5, order: 5},
  {id: 6, order: 6},
  {id: 51, order: 1, parent_id: 5},
  {id: 52, order: 2, parent_id: 5},
  {id: 53, order: 3, parent_id: 5})

Event::TargetGroup::Translation.seed_once(:event_target_group_id, :locale,
  {event_target_group_id: 1,
   locale: "de",
   label: "Kinder (KiBe)",
   description: "Kinderprogramm"},
  {event_target_group_id: 2,
   locale: "de",
   label: "Jugend (JO)",
   description: "Jugendprogramm"},
  {event_target_group_id: 3,
   locale: "de",
   label: "Jung-Erwachsene",
   description: "Jung-Erwachsenenprogramm"},
  {event_target_group_id: 4,
   locale: "de",
   label: "Erwachsene",
   description: "Erwachsenenprogramm"},
  {event_target_group_id: 5,
   locale: "de",
   label: "Senioren",
   description: "Seniorenprogramm"},
  {event_target_group_id: 6,
   locale: "de",
   label: "Familien (FaBe)",
   description: "Familienprogramm"},
  {event_target_group_id: 51,
   locale: "de",
   label: "Senioren A",
   description: "Senioren A-Programm"},
  {event_target_group_id: 52,
   locale: "de",
   label: "Senioren B",
   description: "Senioren B-Programm"},
  {event_target_group_id: 53,
   locale: "de",
   label: "Senioren C",
   description: "Senioren C-Programm"})

Event::Trait.seed_once(:id,
  {id: 1, order: 1},
  {id: 2, order: 2},
  {id: 3, order: 3},
  {id: 4, order: 4},
  {id: 5, order: 5},
  {id: 11, order: 1, parent_id: 1},
  {id: 12, order: 2, parent_id: 1},
  {id: 13, order: 3, parent_id: 1},
  {id: 21, order: 1, parent_id: 2},
  {id: 31, order: 1, parent_id: 3},
  {id: 32, order: 2, parent_id: 3},
  {id: 41, order: 1, parent_id: 4},
  {id: 42, order: 2, parent_id: 4},
  {id: 43, order: 3, parent_id: 4},
  {id: 44, order: 4, parent_id: 4},
  {id: 51, order: 1, parent_id: 5},
  {id: 52, order: 2, parent_id: 5},
  {id: 53, order: 3, parent_id: 5},
  {id: 54, order: 4, parent_id: 5},
  {id: 55, order: 5, parent_id: 5})

Event::Trait::Translation.seed_once(:event_trait_id, :locale,
  {event_trait_id: 1,
   locale: "de",
   label: "Organisation & Durchführung"},
  {event_trait_id: 11,
   locale: "de",
   label: "Mit Bergführer"},
  {event_trait_id: 12,
   locale: "de",
   label: "Organisiert von SAC & JO"},
  {event_trait_id: 13,
   locale: "de",
   label: "Spez. Kostenberechnung"},
  {event_trait_id: 2,
   locale: "de",
   label: "Struktur & Dauer"},
  {event_trait_id: 21,
   locale: "de",
   label: "Mehrtägig / Lager"},
  {event_trait_id: 3,
   locale: "de",
   label: "Anreise & Logistik"},
  {event_trait_id: 31,
   locale: "de",
   label: "Anreise mit ÖV"},
  {event_trait_id: 32,
   locale: "de",
   label: "Anreise am Vorabend"},
  {event_trait_id: 4,
   locale: "de",
   label: "Art / thematische Ausrichtung"},
  {event_trait_id: 41,
   locale: "de",
   label: "Training"},
  {event_trait_id: 42,
   locale: "de",
   label: "Exkursion"},
  {event_trait_id: 43,
   locale: "de",
   label: "Arbeitseinsatz"},
  {event_trait_id: 44,
   locale: "de",
   label: "Versammlung"},
  {event_trait_id: 5,
   locale: "de",
   label: "Zielgruppe / Eignung"},
  {event_trait_id: 51,
   locale: "de",
   label: "Geeignet für Tourenleitende & Aspiranten"},
  {event_trait_id: 52,
   locale: "de",
   label: "Geeignet für Frauen"},
  {event_trait_id: 53,
   locale: "de",
   label: "Geeignet für Menschen mit Einschränkungen"},
  {event_trait_id: 54,
   locale: "de",
   label: "Geeignet für Schnuppergäste"},
  {event_trait_id: 55,
   locale: "de",
   label: "Geeignet für Spontane"})
