# frozen_string_literal: true

#  Copyright (c) 2025, Schweizer Alpen-Club. This file is part of
#  hitobito_sac_cas and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sac_cas.

Event::Discipline.seed_once(:id,
  {id: 1, order: 1},
  {id: 2, order: 2},
  {id: 3, order: 3},
  {id: 4, order: 4},
  {id: 11, order: 1, parent_id: 1},
  {id: 12, order: 2, parent_id: 1},
  {id: 13, order: 3, parent_id: 1},
  {id: 21, order: 1, parent_id: 2},
  {id: 22, order: 2, parent_id: 2},
  {id: 31, order: 1, parent_id: 3},
  {id: 32, order: 2, parent_id: 3},
  {id: 33, order: 3, parent_id: 3},
  {id: 34, order: 4, parent_id: 3},
  {id: 41, order: 1, parent_id: 4})

Event::Discipline::Translation.seed_once(:event_discipline_id, :locale,
  {event_discipline_id: 1,
   locale: "de",
   label: "Wandern",
   description: "Das Wandern ist des Müllers Lust"},
  {event_discipline_id: 2,
   locale: "de",
   label: "Hochtouren",
   description: "Obeuse"},
  {event_discipline_id: 3,
   locale: "de",
   label: "Klettern",
   description: "Chräsmä u Stägärä"},
  {event_discipline_id: 4,
   locale: "de",
   label: "Höhle",
   description: "Speläologie"},
  {event_discipline_id: 11,
   locale: "de",
   label: "Wanderweg",
   description: "Gemütlich dem Weg entlang"},
  {event_discipline_id: 12,
   locale: "de",
   label: "Bergtour",
   description: "Über Stock und Stein"},
  {event_discipline_id: 13,
   locale: "de",
   label: "Schneeschuhwandern",
   description: "Im Schnee läuft es sich besser mit grösserer Fläche"},
  {event_discipline_id: 21,
   locale: "de",
   label: "Skihochtouren",
   description: "Zwei Latten"},
  {event_discipline_id: 22,
   locale: "de",
   label: "Snowboardhochtouren",
   description: "Ein Brett"},
  {event_discipline_id: 31,
   locale: "de",
   label: "Fels",
   description: "Im harten Stein"},
  {event_discipline_id: 32,
   locale: "de",
   label: "Eis",
   description: "Schattig und kalt"},
  {event_discipline_id: 33,
   locale: "de",
   label: "Indoor",
   description: "Immer trocken, immer warm"},
  {event_discipline_id: 34,
   locale: "de",
   label: "Mehrseillängen",
   description: "Länger ist mehr"},
  {event_discipline_id: 41,
   locale: "de",
   label: "Höhle",
   description: "Speläologie"})

Event::TargetGroup.seed_once(:id,
  {id: 1, order: 1},
  {id: 2, order: 2},
  {id: 3, order: 3},
  {id: 4, order: 4},
  {id: 5, order: 5},
  {id: 6, order: 6},
  {id: 51, order: 1, parent_id: 5},
  {id: 52, order: 2, parent_id: 5},
  {id: 53, order: 3, parent_id: 5})

Event::TargetGroup::Translation.seed_once(:event_target_group_id, :locale,
  {event_target_group_id: 1,
   locale: "de",
   label: "Kinder (KiBe)",
   description: "Kinderprogramm"},
  {event_target_group_id: 2,
   locale: "de",
   label: "Jugend (JO)",
   description: "Jugendprogramm"},
  {event_target_group_id: 3,
   locale: "de",
   label: "Jung-Erwachsene",
   description: "Jung-Erwachsenenprogramm"},
  {event_target_group_id: 4,
   locale: "de",
   label: "Erwachsene",
   description: "Erwachsenenprogramm"},
  {event_target_group_id: 5,
   locale: "de",
   label: "Senioren",
   description: "Seniorenprogramm"},
  {event_target_group_id: 6,
   locale: "de",
   label: "Familien (FaBe)",
   description: "Familienprogramm"},
  {event_target_group_id: 51,
   locale: "de",
   label: "Senioren A",
   description: "Senioren A-Programm"},
  {event_target_group_id: 52,
   locale: "de",
   label: "Senioren B",
   description: "Senioren B-Programm"},
  {event_target_group_id: 53,
   locale: "de",
   label: "Senioren C",
   description: "Senioren C-Programm"})

Event::TechnicalRequirement.seed_once(:id,
  {id: 1, order: 1},
  {id: 2, order: 2},
  {id: 3, order: 3},
  {id: 4, order: 4},
  *(5 * 6 + 1).times.map do |i|
    {id: 10 + i, order: i, parent_id: 1}
  end,
  *6.times.map do |i|
    {id: 50 + i, order: i, parent_id: 2}
  end,
  *7.times.map do |i|
    {id: 60 + i, order: i, parent_id: 3}
  end,
  *6.times.map do |i|
    {id: 70 + i, order: i, parent_id: 4}
  end)

Event::TechnicalRequirement::Translation.seed_once(:event_technical_requirement_id, :locale,
  {event_technical_requirement_id: 1,
   locale: "de",
   label: "Französische Kletterskala",
   description: "Klettern"},
  {event_technical_requirement_id: 2,
   locale: "de",
   label: "Wanderskala",
   description: "Wandern"},
  {event_technical_requirement_id: 3,
   locale: "de",
   label: "Skitourenskala",
   description: "Skitouren"},
  {event_technical_requirement_id: 4,
   locale: "de",
   label: "Singletrailskala",
   description: "Mountain Bike"},
  *2.times.flat_map do |i|
    %w[a b c].each_with_index.map do |grade, j|
      {event_technical_requirement_id: 10 + i * 3 + j,
       locale: "de",
       label: "#{i + 3}#{grade}"}
    end
  end,
  *4.times.flat_map do |i|
    %w[a a+ b b+ c c+].each_with_index.map do |grade, j|
      {event_technical_requirement_id: 16 + i * 6 + j,
       locale: "de",
       label: "#{i + 5}#{grade}"}
    end
  end,
  {event_technical_requirement_id: 10 + 5 * 6,
   locale: "de",
   label: "9a"},
  *6.times.map do |i|
    {event_technical_requirement_id: 50 + i,
     locale: "de",
     label: "T#{i + 1}"}
  end,
  *%w[L WS ZS S SS AS EX].each_with_index.map do |grade, i|
    {event_technical_requirement_id: 60 + i,
     locale: "de",
     label: grade}
  end,
  *6.times.map do |i|
    {event_technical_requirement_id: 70 + i,
     locale: "de",
     label: "S#{i}"}
  end)

Event::FitnessRequirement.seed_once(:id,
  {id: 1, order: 1},
  {id: 2, order: 2},
  {id: 3, order: 3},
  {id: 4, order: 4},
  {id: 5, order: 5})

Event::FitnessRequirement::Translation.seed_once(:event_fitness_requirement_id, :locale,
  {event_fitness_requirement_id: 1,
   locale: "de",
   label: "A - nicht anstrengend",
   short_description: "0-3h Totalzeit",
   description: "0-3h Totalzeit"},
  {event_fitness_requirement_id: 2,
   locale: "de",
   label: "B - wenig anstrengend",
   short_description: "3-5h Totalzeit; bis ca. 800HM Aufstieg",
   description: "3-5h Totalzeit; bis ca. 800HM Aufstieg"},
  {event_fitness_requirement_id: 3,
   locale: "de",
   label: "C - ziemlich anstrengend",
   short_description: "4-7h Totalzeit; ca. 800-1300HM Aufstieg",
   description: "5-7h Totalzeit; ca. 800-1300HM Aufstieg"},
  {event_fitness_requirement_id: 4,
   locale: "de",
   label: "D - anstrengend",
   short_description: "6-10h Totalzeit; ca. 1300-1600HM Aufstieg",
   description: "6-10h Totalzeit; ca. 1300-1600HM Aufstieg"},
  {event_fitness_requirement_id: 5,
   locale: "de",
   label: "E - sehr anstrengend",
   short_description: "über 10h Totalzeit; Aufstieg mehr als 1600HM",
   description: "über 10h Totalzeit; Aufstieg mehr als 1600HM"})
